[supervisord]
nodaemon=true

[program:flask]
command=python3 app.py
directory=/app
environment=FLASK_ENV=development,FLASK_DEBUG=1
autostart=true
autorestart=true

[program:react]
command=npm start
directory=/app/frontend
autostart=true
autorestart=true
